### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by shelune** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#2]
At question 14 (https://github.com/nishant8BITS/123-Essential-JavaScript-Interview-Question#14-what-will-be-the-output-of-below-code), there are 2 lines of 'Boolean + Number -> Addition'

Should one be 'Boolean + Boolean -> Addition'?

**Comment by chanpete** [comment]
I saw one more.

At [question 20](https://github.com/nishant8BITS/123-Essential-JavaScript-Interview-Question#20-what-is-the-instanceof-operator-in-javascript-what-would-be-the-output-of-below-code)

> Here name instanceof String is true since dog inherits from String.prototype

Should be "since **name** inherits from String.prototype"

**Comment by chanpete** [comment]
And [question 24](https://github.com/nishant8BITS/123-Essential-JavaScript-Interview-Question#question-24) is duplicated with [question 5](https://github.com/nishant8BITS/123-Essential-JavaScript-Interview-Question#5-write-a-mul-function-which-will-properly-when-invoked-as-below-syntax).

**Comment by chanpete** [comment]
And [question 28](https://github.com/nishant8BITS/123-Essential-JavaScript-Interview-Question#question-28)

> **Method 2**: Object Literal
> Object Literal is bast way to create an object

does it mean the best way?

**Comment by nishant8BITS** [comment]
Thanks @shelune and @chanpete I did the changes :+1:

**Comment by Mottie** [comment]
Question 24 is still a duplicate of question 5.

Also [Question 27](https://github.com/nishant8BITS/123-Essential-JavaScript-Interview-Question#question-27) has a typo in the first sentence:

>  you will probably is more than any others

I think "is" should be changed to "use".
