### ISSUE TITLE
Question 23 

### ISSUE THREAD

**Issue by 0xfirelight** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#23]
Hey there, description in question 23 needs a bit of adjustment 

> Let say `new User("xyz")` created a object called `foo` and returned now `foo["location"]` would be assigned value as `USA` and person is referencing to `foo["location"]`.

Here, `person` is not referencing `foo["location"]`, instead it is being assigned the result of Assignment Operator `=` which in this case returns string 'USA'. Assignment operator always returns the value of the expression on the right, as described here: 
[ECMAScript Specification](http://www.ecma-international.org/ecma-262/6.0/#sec-assignment-operators-runtime-semantics-evaluation) , pt 12.14.4

Otherwise it's totally correct, thanks for great work!

**Comment by ganqqwerty** [comment]
This is absolutely right, thanks for the important correction!
