### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by bendtherules** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#25]
I couldn't find much activity in this repository for the last few months. There are quite a few issues and pull requests pending, which didn't receive any attention. 

@nishant8BITS What are your thoughts regarding this? I understand that this was also meant to be released as a commercial project, and you are probably unable to spend more time on the repo.

I consider this project to be a very important resource for interviews and have greatly benefited from it. I would be really happy to help out with the maintenance if you would like that.

**Comment by ganqqwerty** [comment]
I took over the repository and will finish the book! Nishant will still help whenever he can.
