### ISSUE TITLE
Question 16. What will be the output of the following code?

### ISSUE THREAD

**Issue by eduardomoroni** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#31]
![image](https://user-images.githubusercontent.com/823150/38469480-e782bf62-3b2b-11e8-9c0a-7acac69bd51d.png)

not exactly

![image](https://user-images.githubusercontent.com/823150/38469478-d5da4582-3b2b-11e8-990b-ffeb92d57926.png)

**Comment by ganqqwerty** [comment]
funny! which browser did you use to get this result? Can you try it again in chrome in a new tab? It seems that you declared variable `bar` before somewhere?

**Comment by akshayjai1** [comment]
I got the same console message. Seems like Javascript throws away the function name when function is written as expression, please find attached image
![screen shot 2018-06-24 at 8 29 58 pm](https://user-images.githubusercontent.com/5356052/41820314-880a9c54-77ed-11e8-9477-b100b98dffb0.png)

**Comment by akshayjai1** [comment]
You can also create one more question on similar lines,  i.e. what will be output of following two lines
![screen shot 2018-06-24 at 8 43 13 pm](https://user-images.githubusercontent.com/5356052/41820424-4dad8c7c-77ef-11e8-967c-87d08085550a.png)

**Comment by ganqqwerty** [comment]
Answer to your first message: 

> well, besically you replaced `bar` with `y` and got the same result as in the book. 


Answer to your second message: 

> Wait a minute, your second message doesn't explain anything, check out what x is, it's just an object.   It's also kinda convoluted, because you have x in the name of a variable and x in the name of a function. The new function construction is not a way to create functions, the result of a new operator will just be an empty object. 

What I don' understand is why 3 is printed, hmm...

**Comment by ganqqwerty** [comment]
@eduardomoroni still need help from you with this question

**Comment by eduardomoroni** [comment]
Sorry @ganqqwerty, Just tried again:
I'm using Google Chrome `Version 70.0.3538.77 (Official Build) (64-bit)`
![image](https://user-images.githubusercontent.com/823150/48316903-ebbd6a00-e5e9-11e8-8a0a-b811e88f311b.png)

I'm getting: `Uncaught ReferenceError: bar is not defined` which is the expected output.
