### ISSUE TITLE
Could Use Improvement

### ISSUE THREAD

**Issue by melvinwallerjr** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#35]
I'd like to commend you for the compilation of the JavaScript examples. I like the variety you provide and they give some good reminders on common pitfalls. I do, however, implore you to review and update some of your examples. Some are inaccurate or have outright errors.

Question 48 for example assigns an object to a reserved word, location. And then the 'Method 1', ES6 example for this is not only a poor example of ES6, it is also errored. A good example would be:
`const merge = (toObj, fromObj) => Object.assign(toObj, fromObj);`

Keep up the good work. Just be sure that it is correct. :)

**Comment by ganqqwerty** [comment]
Thanks, good suggestion, I will fix this

**Comment by ganqqwerty** [comment]
fixedm I used your example, thanks again
