### ISSUE TITLE
SetTiemout in for loop not print consecutive values

### ISSUE THREAD

**Issue by SachAtTiwari** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#36]
for (var i = 1; i <= 2; i++) {
    setTimeout(function() { alert(i) }, 100);
}

The use case for IIFE
Add if found suitable

**Comment by ganqqwerty** [comment]
Yeah, it’s a good one if you don’t have es6 block scoping with let/const. Thanks!

**Comment by ganqqwerty** [comment]
do you have some question in mind where I can add this example?
