### ISSUE TITLE
Question 2 function expression

### ISSUE THREAD

**Issue by ytaminE** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#43]
For the function expression in Q2

```javascript
var myFunc1 = new function() {}
var myFunc2 = new function whatever() {} // whatever is not a variable here
```
I think it would be better to use something like the code below to distinguish the 'function' and the 'Function' object

```javascript
var myFunc1 = function() {}
var myFunc2 = function whatever() {}
var myFunc3 = new Function ('a', 'b', 'return a+b')
```

Sorry, I don't understand why using new function(...) {...} rather than new Function()

**Comment by ganqqwerty** [comment]
the whole question will be replaced

**Comment by ganqqwerty** [comment]
done
