### ISSUE TITLE
Function Call is incorrect in Question 25, Example 1

### ISSUE THREAD

**Issue by jappreetS** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#44]
As you can see in the attached snapshot here, you have added **myMethod** and calling **display** method which is not their in the **obj1** object which can result in an error.

![question25](https://user-images.githubusercontent.com/32400976/42814378-a4d53424-89e1-11e8-9b77-5cf5c2ce92d4.png)

**Comment by richi1717** [comment]
I noticed that as well and am about to open a pr for that.

**Comment by ganqqwerty** [comment]
Done! Thanks for being watchful!!!
