### ISSUE TITLE
If condition statement evaluate using eval?

### ISSUE THREAD

**Issue by stevemao** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#5]
> If condition statement evaluate using `eval`

I'm not sure if this is correct? According to mdn, 

> if (condition)
> condition
> An expression that evaluates to true or false.

My understand is `function f() {}` here is an [function expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/function) instead of [function declaration](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function) so `f` is not a variable. Hence it's `undefined`. 

Can you provide any reference of "If condition statement evaluate using `eval`"?

**Comment by sairion** [comment]
I have also seen someone asking is this true on some forum. I don't think so, there is no mention of global `eval()` function being used in `IfStatement` in ECMA-262 https://es5.github.io/#x12.5

**Comment by ganqqwerty** [comment]
I read the standard and I agree that's you're right. I'm fixing it.
