### ISSUE TITLE
Question 3. Missing declaration of 'emp1', 'emp2', 'emp3' and 'displayIncreasedSalary'

### ISSUE THREAD

**Issue by kumaran-14** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#58]
`emp1`, `emp2`, `emp3` and `displayIncreasedSalary` are all mentioned in the explanation of the example in question 3, but not actually mentioned in the example

**Comment by ganqqwerty** [comment]
thanks! I will fix it!

**Comment by ganqqwerty** [comment]
I rewrote the question 3 completely, I hope it's clearer now!
