### ISSUE TITLE
Question 29: check for null

### ISSUE THREAD

**Issue by vibl** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#59]
In "Question 29. Write a function called deepClone which takes an object and creates a object copy of it.", the deepClone function should check for a `null` value:

`if( typeof object[key] === 'object' && object[key] !== null )`...

What's more, we usually want to also check for `hasOwnProperty()`.

**Comment by ganqqwerty** [comment]
fixed check for null. About hasownproperty I'm not that sure...
