### ISSUE TITLE
17 item

### ISSUE THREAD

**Issue by o-mar** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#6]
Hi,
I think it is bad example to show Function Declaration in if/else block.
http://stackoverflow.com/questions/10069204/function-declarations-inside-if-else-statements
Thanks!

**Comment by ganqqwerty** [comment]
thanks! I'm adding the note about compatibility with the different version of ES standard

**Comment by ganqqwerty** [comment]
you know what: I will just remove that code block because it is just a weird practice to do that.
