### ISSUE TITLE
Question 44: shouldn't `appLog("Some error message")` be enough?

### ISSUE THREAD

**Issue by vibl** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#60]
In 'Question 44. Write a log function which will add prefix (your message) to every message you log using console.log ?', shouldn't `appLog("Some error message")` be enough as a final statement instead of `console.log(appLog("Some error message"))`?

**Comment by ganqqwerty** [comment]
thanks, fixed. Actually pretty stupid question, can you help me with reformulating it?
