### ISSUE TITLE
Question 48

### ISSUE THREAD

**Issue by nomean42** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#61]
looks like mistake:
`Method 1: Using ES6, Object assign method`
![screenshot 2018-10-25 at 11 12 02](https://user-images.githubusercontent.com/13020611/47475689-d94fdc00-d846-11e8-8375-ea17e2c113c6.png)

**Comment by ganqqwerty** [comment]
oops it's supposed to be an arrow function

**Comment by ganqqwerty** [comment]
thanks so much for your help!
