### ISSUE TITLE
Coding Questions -> Arrays -> 2. What would be the output of following code?

### ISSUE THREAD

**Issue by nomean42** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#63]
```
(function() {
	var array1 = [];
	var array2 = new Array(100);
	var array3 = new Array(['1',2,'3',4,5.6]);
	console.log(array1);
	console.log(array2);
	console.log(array3);
	console.log(array3.length);
}());
```

1. [] [] [Array[5]] 1
2. [] [undefined × 100] Array[5] 5
3. [] [] ['1',2,'3',4,5.6] 5
4. [] [] [Array[5]] 5

Answer: 1) [] [] [Array[5]] 1

Correct is **[] [undefined × 100] [Array[5]] 1**

**Comment by ganqqwerty** [comment]
Oops , it seems that you’re right! I will check it again when I have access to the computer

**Comment by ganqqwerty** [comment]
thanks so much!
