### ISSUE TITLE
Function Question mistake

### ISSUE THREAD

**Issue by LianJilu** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#67]
write one more console.log, remove one function invoked or replace return of one in function

**Comment by ganqqwerty** [comment]
I don't get it, please elaborate

**Comment by LianJilu** [comment]
![image](https://user-images.githubusercontent.com/25577583/49790136-7bc90d80-fd68-11e8-9601-f3a55ddbfed5.png)
repeated console.log

**Comment by nishant8BITS** [comment]
@LianJilu This is intentionally added, Answer is 4) undefined true
