### ISSUE TITLE
Can you explain me the output of following JavaScript Code?

### ISSUE THREAD

**Issue by Soorajgit** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#75]
var count = function () {
	this.c = 0 ;
var add = function () {
	return ++this.c;
	};
this.addNum = function (n) {
for(i= 0; i<n ; i++) {
	add();
}
return this.c ;
	};
}
console.log(new count().addNum(10));

**Comment by tigertv** [comment]
Why do you ask that here?

**Comment by ganqqwerty** [comment]
We have similar questions in the list, just check it out around the Closures section. Also, soon my flashcards will be printed and you'll be able to revise your knowledge in a paper form!
