### ISSUE TITLE
Question 49

### ISSUE THREAD

**Issue by givehug** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#78]
Hi, thanks for the questionnaire!

A small correction:

```
// Create non-enumerable property
Object.defineProperty(person, 'phoneNo',{
	value : '8888888888',
	enumerable: false
})
```

> Changing non-enumerable property value will return error in strict mode. In non-strict mode it won't through any error but it won't change the value of phoneNo.

Value of phoneNo won't change because 'writable' descriptor is false by default, not because  'enumerable' is false.

If you had:
```
Object.defineProperty(person, 'phoneNo',{
	value : '8888888888',
	enumerable: false,
        writable: true,
})
```
you would be able to change property value.

**Comment by ganqqwerty** [comment]
thanks for that, can you please create a PR?

**Comment by givehug** [comment]
> thanks for that, can you please create a PR?

here you go
