### ISSUE TITLE
Question 38

### ISSUE THREAD

**Issue by eshin714** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#8]
Question 38 seems to be wrong.

emp1.displayName = function() {
    console.log('xyz-Anonymous');
};

employee.displayName();// "xyz-Anonymous"
emp1.displayName(); // "Nishant"

These two should be switched.

employee.displayName();// "Nishant"
emp1.displayName(); // "xyz-Anonymous"

**Comment by ganqqwerty** [comment]
thanks it's fixed
